# -*- coding: utf-8 -*-
"""save_model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QLhbKatukzap_Aq94j1KOopBTMHNlbd
"""

model.save('gesture.h5')