# -*- coding: utf-8 -*-
"""imagedatagenerator_library

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QLhbKatukzap_Aq94j1KOopBTMHNlbd
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator