# -*- coding: utf-8 -*-
"""configureimagedatagenerator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QLhbKatukzap_Aq94j1KOopBTMHNlbd
"""

train_datagen = ImageDataGenerator(rescale=1./255,
                                   shear_range=0.2,
                                   zoom_range=0.2,
                                   horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)