# -*- coding: utf-8 -*-
"""initialize_model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QLhbKatukzap_Aq94j1KOopBTMHNlbd
"""

model = Sequential()